### ISSUE TITLE
JsonApi Integration Concern: Complexity of responses

### ISSUE THREAD

**Issue by bkuhl** [realpage/lumen-starter#38]
If I interpreted @anitayip's concern correctly during the Lumen Starter discussion, responses for json api can be exhaustive and it may be difficult to maintain the documentation due to the extensive relations.  Is this a fair assessment of your concern?

**Comment by AnitaYip** [comment]
To be honest, the complexity of JSON API was assessed based on the example given on its website home page. Unless we implement it for our own api, we wont be able to conclusively say it is overly complex. And Srinivas (@sbethi) has few concerns about it on how we can have the existing systems migrate over. That all said, I do have few questions regarding it:
1) @jlaswell Are you aware of any third party libraries available for using JSON-API with Java, Ruby on Rails, .NET? Since it is a standard, I assume that there might be. If that is the case, it answers Srinivas's concern above. Please confirm. (Sorry didn't get a chance to do any research on this yet).
2) What kind of role does JSON-API plays in POST/PUT incoming requests? When we return json api in the response, we usually expect the client to use the same object structure to create/update the data. So, with JSON-API in place, is the client supposed to strip off the meta tags before transforming to their object structure? Should we expect these meta tags in the POST/PUT request body or can we safely ignore them?

**Comment by jlaswell** [comment]
1. Good question! There is actually an [implementations listing](http://jsonapi.org/implementations/) on the official site along with a lot more information about each package/library as well as a small description. There is a lot of good content throughout the entire site, so I suggest @sbethi read through it. You too if you also have concerns of course.
  2. IMO, there are a few things to take into account here. The [CRUD section](http://jsonapi.org/format/#crud) gives some good points, but here's my opinionated tl;dr.
    - POST request:
      - accept a single resource object with at least a `type` member
      - enforce required `data` attributes and return a 422 Unprocessable Entity with an [Error response](http://jsonapi.org/format/#errors) when missing required attributes
      - ignore metadata, but that's up to you all on how to handle it of course
    - PUT request:
      - used to [replace an entire resource](https://laracasts.com/discuss/channels/general-discussion/whats-the-differences-between-put-and-patch?page=1) for a specific resource via its `id`
      - same criteria applies for the POST request, but with the above requirement as well
    - PATCH request:
      - update a delta of a specific resource via its `id`
      - this allows excluding required fields in the request, as they are already set for the updating resource

**Comment by bkuhl** [comment]
Is there anymore to discuss here or should we close this out?

**Comment by bkuhl** [comment]
Closing this one as well.
