### ISSUE TITLE
Is it possible to build multi-module structure for Lumen projects?

### ISSUE THREAD

**Issue by AnitaYip** [realpage/lumen-starter#52]
Most of the Foundation's enterprise services are deployed separately, there will always be some common code (most likely in the super classes or util classes) that can be shared across the different enterprise api applications. Is it possible to have this common code as a separate module which can be used as a dependency for the main module to avoid code replication in each module?

**Comment by jlaswell** [comment]
For sure! [Module 10](https://github.com/realpage/training-modules/blob/master/Module-10.md) has some good training on how to accomplish that. You could exclude the info on GUI stuff. The [json-api middleware](https://github.com/realpage/json-api-for-lumen) is a good example of how to do this for lumen.

**Comment by bkuhl** [comment]
It's so exciting you're asking these kinds of questions!!

On May 20, 2016 4:44 PM, John Laswell <notifications@github.com> wrote:

For sure! Module 10<https://github.com/realpage/training-modules/blob/master/Module-10.md> has some good training on how to accomplish that. You could exclude the info on GUI stuff. The json-api middleware<https://github.com/realpage/json-api-for-lumen> is a good example of how to do this for lumen.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub<https://github.com/realpage/lumen-starter/issues/52#issuecomment-220714005>

________________________________

This message is intended only for the use of the individual(s) or entity to which it is addressed and may contain information that is privileged, confidential, and/or proprietary to RealPage and its affiliated companies. If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution, forwarding or copying of this communication is prohibited without the express permission of the sender. If you have received this communication in error, please notify the sender immediately and delete the original message.

**Comment by AnitaYip** [comment]
Excellent, Thanks!! I will create one for the enterprise services. I have looked at json-api-for-lumen. Is it supposed to be how we use the json-api related functionality? That brings me to another question. We have different project repos created based off of lumen-starter already. How do we get any changes made in Lumen-starter into these individual repos?

**Comment by bkuhl** [comment]
The package `json-api-for-lumen` currently contains a middleware that requires correct content types.

Unfortunately these will have to happen manually.  I'd suggest subscribing to this repo so you get notified whenever there's a pull request.  This is why John created `json-api-for-lumen`, so every project will have it, but updates are versioned/distributed.  I'm going to update the readme to reflect this.
